# default
---
spring:
  profiles: default

kafka:
  server:
    topic: ECC-TCLD-Topic-AD
    url: com-kafka-qa.com.homedepot.com:9092
    connector: COM_ECC_XML_MESSAGE_TOPIC_AD
    json: COM_ECC_JSON_MESSAGE_TOPIC_AD

# test
---
spring:
  profiles: test

kafka:
  server:
    topic: ECC-TCLD-Topic-AD
    url: com-kafka-qa.com.homedepot.com:9092
    connector: COM_ECC_XML_MESSAGE_TOPIC_AD
    json: COM_ECC_JSON_MESSAGE_TOPIC_AD



#development
---
spring:
  profiles: development

kafka:
  server:
    topic: ECC-TCLD-Topic-AD
    url: com-kafka-qa.com.homedepot.com:9092
    connector: COM_ECC_XML_MESSAGE_TOPIC_AD
    json: COM_ECC_JSON_MESSAGE_TOPIC_AD



# QA
---
spring:
  profiles: qa

kafka:
  server:
    topic: ECC-TCLD-Topic-QA
    url: com-kafka-qa.com.homedepot.com:9092
    connector: COM_ECC_XML_MESSAGE_TOPIC
    json: COM_ECC_JSON_MESSAGE_TOPIC

  # QP
---
spring:
  profiles: qp

kafka:
  server:
    topic: ECC-TCLD-Topic-QP
    url: com-kafka-qp.com.homedepot.com:9092
    connector: COM_ECC_XML_MESSAGE_TOPIC
    json: COM_ECC_JSON_MESSAGE_TOPIC


  # PRODUCTION
---
spring:
  profiles: production

kafka:
  server:
    topic: ECC-TCLD-Topic
    url: com-kafka-pr.com.homedepot.com:9092
    connector: COM_ECC_XML_MESSAGE_TOPIC
    json: COM_ECC_JSON_MESSAGE_TOPIC


  # PRODUCTION-EB
---
spring:
  profiles: production-eb

kafka:
  server:
    topic: ECC-TCLD-Topic
    url: com-kafka-prodssc.homedepot.com:9092
    connector: COM_ECC_XML_MESSAGE_TOPIC
    json: COM_ECC_JSON_MESSAGE_TOPIC
